version: '3'
services:

  #Nginx Service
  webserver:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: nginx:1
    container_name: webserver
#    restart: unless-stopped
    tty: true
    depends_on:
      - app 
    ports:
      - "8081:80"
    networks:
      - app-network

  #app Service
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: webapp:1
    container_name: app
#    restart: unless-stopped
    tty: true
    depends_on:
      - db 
    ports:
      - 8082:8080
    networks:
      - app-network


  #MySQL Service
  db:
    build:
      context: .
      dockerfile: Dockerfile-sql
    image: mysql:1
    container_name: db
#    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge


