FROM ubuntu

ENV TZ=Asia/Dubai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update \
    && apt install -y tzdata \
    && apt-get update \
    &&  apt-get dist-upgrade -y \
    && apt-get install apache2 -y \
    && apt-get install python3-pip git -y \ 
    && pip3 install pymysql \
    && a2dismod mpm_event \
    && a2enmod mpm_prefork cgi \
    && service apache2 restart 

ADD "https://s3.amazonaws.com/richbourg-s3/mtwa/app/ports.conf"  /etc/apache2/sites-enabled/
ADD "https://s3.amazonaws.com/richbourg-s3/mtwa/app/000-default.conf" /etc/apache2/
RUN service apache2 restart
RUN git clone https://gitlab.com/crest1/devops_test.git
RUN cd devops_test && bash ./install.sh
